$primary = rgb(e6b450)
$surface = rgb(0b0e14)
$secondary = rgb(aad94c)
$error = rgb(d95757)
$tertiary = rgb(39bae6)
$surface_lowest = rgb(0e1218)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
