# --- VARIABLES ---
$foreground = rgb(cdd6f4)

# BACKGROUND
background {
    monitor =
    path = /home/hammsvietro/wallpapers/tarantula_nebula.png
    contrast = 1
    brightness = 0.5
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

# GENERAL
general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = false
    grace = 0
    disable_loading_bar = true
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    
   
    outer_color = rgba(ffffff00)
    inner_color = rgba(ffffff33)
    check_color = rgb(cc8822)
    font_color = $foreground
    
    fade_on_empty = false
    rounding = -1
    placeholder_text = <i><span foreground="##cdd6f4">Input Password...</span></i>
    hide_input = false
    position = 0, -200
    halign = center
    valign = center
}

# DATE
label {
  monitor =
 
  text = cmd[update:3600000] echo "$(date +"%A, %B %d")"
  color = rgba(f2f3f4bf)
  font_size = 22
  font_family = JetBrains Mono
  position = 0, 300
  halign = center
  valign = center
}

# TIME
label {
  monitor =
  text = cmd[update:30000] echo "$(date +"%-I:%M")"
  color = rgba(f2f3f4bf)
  font_size = 95
  font_family = JetBrains Mono Extrabold
  position = 0, 200
  halign = center
  valign = center
}
