general {
    lock_cmd = noctalia-shell ipc call lockScreen lock
    before_sleep_cmd = noctalia-shell ipc call lockScreen lock    
    after_sleep_cmd = hyprctl dispatch dpms on  
}

listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 600
    on-timeout = noctalia-shell ipc call lockScreen lock
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
}/
